function BtAyuda(x, y, w, h){
	this.x = x;
	this.y = y;
	this.w = w;
	this.h = h;

	var wi = 12.0;
	var he = 12.0;
	var negro2 = "rgb(20, 35, 30)";
	
	this.dibu3 = function(ctx){

		ctx.strokeStyle = 'black';
		ctx.lineWidth = 2;
		//boton
		ctx.fillStyle = negro2;
		ctx.beginPath(); 
		ctx.moveTo(this.x+0.5/wi*this.w, this.y+0.5/he*this.h); 
		ctx.lineTo(this.x+4.0/wi*this.w, this.y+0.5/he*this.h);
		ctx.lineTo(this.x+4.5/wi*this.w, this.y+1.0/he*this.h); 
		ctx.lineTo(this.x+4.5/wi*this.w, this.y+2.5/he*this.h); 
		ctx.lineTo(this.x+4.0/wi*this.w, this.y+3.0/he*this.h);
		ctx.lineTo(this.x+0.5/wi*this.w, this.y+3.0/he*this.h);
		ctx.lineTo(this.x+0.0/wi*this.w, this.y+2.5/he*this.h);
		ctx.lineTo(this.x+0.0/wi*this.w, this.y+1.0/he*this.h);
		ctx.closePath(); 
		ctx.stroke();
		ctx.fill();

		//letra A
		ctx.fillStyle = 'red';
		ctx.beginPath(); 
		ctx.moveTo(this.x+1.0/wi*this.w, this.y+1.0/he*this.h); 
		ctx.lineTo(this.x+0.4/wi*this.w, this.y+1.0/he*this.h);
		ctx.lineTo(this.x+0.4/wi*this.w, this.y+2.5/he*this.h); 
		ctx.lineTo(this.x+0.6/wi*this.w, this.y+2.5/he*this.h);
		ctx.lineTo(this.x+0.6/wi*this.w, this.y+2.0/he*this.h);
		ctx.lineTo(this.x+0.8/wi*this.w, this.y+2.0/he*this.h);
		ctx.lineTo(this.x+0.8/wi*this.w, this.y+1.8/he*this.h);
		ctx.lineTo(this.x+0.6/wi*this.w, this.y+1.8/he*this.h);
		ctx.lineTo(this.x+0.6/wi*this.w, this.y+1.2/he*this.h);
		ctx.lineTo(this.x+0.8/wi*this.w, this.y+1.2/he*this.h);
		ctx.lineTo(this.x+0.8/wi*this.w, this.y+2.5/he*this.h);
		ctx.lineTo(this.x+1.0/wi*this.w, this.y+2.5/he*this.h);
		ctx.closePath(); 
		ctx.stroke();
		ctx.fill();
		//letra Y
		ctx.beginPath(); 
		ctx.moveTo(this.x+1.1/wi*this.w, this.y+1.0/he*this.h); 
		ctx.lineTo(this.x+1.45/wi*this.w, this.y+1.8/he*this.h);
		ctx.lineTo(this.x+1.45/wi*this.w, this.y+2.5/he*this.h);
		ctx.lineTo(this.x+1.65/wi*this.w, this.y+2.5/he*this.h); 
		ctx.lineTo(this.x+1.65/wi*this.w, this.y+1.8/he*this.h);
		ctx.lineTo(this.x+2.0/wi*this.w, this.y+1.0/he*this.h);
		ctx.lineTo(this.x+1.8/wi*this.w, this.y+1.0/he*this.h);
		ctx.lineTo(this.x+1.55/wi*this.w, this.y+1.6/he*this.h);
		ctx.lineTo(this.x+1.3/wi*this.w, this.y+1.0/he*this.h);
		ctx.closePath(); 
		ctx.stroke();
		ctx.fill();
		//letra U
		ctx.beginPath(); 
		ctx.moveTo(this.x+2.3/wi*this.w, this.y+1.0/he*this.h); 
		ctx.lineTo(this.x+2.1/wi*this.w, this.y+1.0/he*this.h);
		ctx.lineTo(this.x+2.1/wi*this.w, this.y+2.5/he*this.h); 
		ctx.lineTo(this.x+2.7/wi*this.w, this.y+2.5/he*this.h); 
		ctx.lineTo(this.x+2.7/wi*this.w, this.y+1.0/he*this.h);
		ctx.lineTo(this.x+2.5/wi*this.w, this.y+1.0/he*this.h);
		ctx.lineTo(this.x+2.5/wi*this.w, this.y+2.3/he*this.h);
		ctx.lineTo(this.x+2.3/wi*this.w, this.y+2.3/he*this.h);
		ctx.closePath(); 
		ctx.stroke();
		ctx.fill();
		//letra D
		ctx.beginPath(); 
		ctx.moveTo(this.x+2.8/wi*this.w, this.y+1.0/he*this.h);
		ctx.lineTo(this.x+2.8/wi*this.w, this.y+2.5/he*this.h); 
		ctx.lineTo(this.x+3.2/wi*this.w, this.y+2.5/he*this.h); 
		ctx.lineTo(this.x+3.4/wi*this.w, this.y+2.0/he*this.h);
		ctx.lineTo(this.x+3.4/wi*this.w, this.y+1.5/he*this.h);
		ctx.lineTo(this.x+3.2/wi*this.w, this.y+1.0/he*this.h);
		ctx.lineTo(this.x+3.0/wi*this.w, this.y+1.0/he*this.h);
		ctx.lineTo(this.x+3.0/wi*this.w, this.y+1.2/he*this.h);
		ctx.lineTo(this.x+3.1/wi*this.w, this.y+1.2/he*this.h);
		ctx.lineTo(this.x+3.2/wi*this.w, this.y+1.5/he*this.h);
		ctx.lineTo(this.x+3.2/wi*this.w, this.y+2.0/he*this.h);
		ctx.lineTo(this.x+3.1/wi*this.w, this.y+2.3/he*this.h);
		ctx.lineTo(this.x+3.0/wi*this.w, this.y+2.3/he*this.h);
		ctx.lineTo(this.x+3.0/wi*this.w, this.y+1.0/he*this.h);
		ctx.closePath(); 
		ctx.stroke();
		ctx.fill();
		//letra A
		ctx.beginPath(); 
		ctx.moveTo(this.x+4.1/wi*this.w, this.y+1.0/he*this.h); 
		ctx.lineTo(this.x+3.5/wi*this.w, this.y+1.0/he*this.h);
		ctx.lineTo(this.x+3.5/wi*this.w, this.y+2.5/he*this.h); 
		ctx.lineTo(this.x+3.7/wi*this.w, this.y+2.5/he*this.h);
		ctx.lineTo(this.x+3.7/wi*this.w, this.y+2.0/he*this.h);
		ctx.lineTo(this.x+3.9/wi*this.w, this.y+2.0/he*this.h);
		ctx.lineTo(this.x+3.9/wi*this.w, this.y+1.8/he*this.h);
		ctx.lineTo(this.x+3.7/wi*this.w, this.y+1.8/he*this.h);
		ctx.lineTo(this.x+3.7/wi*this.w, this.y+1.2/he*this.h);
		ctx.lineTo(this.x+3.9/wi*this.w, this.y+1.2/he*this.h);
		ctx.lineTo(this.x+3.9/wi*this.w, this.y+2.5/he*this.h);
		ctx.lineTo(this.x+4.1/wi*this.w, this.y+2.5/he*this.h);
		ctx.closePath(); 
		ctx.stroke();
		ctx.fill();
		 
		//remaches
		ctx.fillStyle = 'grey';
		ctx.beginPath(); 
		ctx.arc(this.x+0.6/wi*this.w, this.y+0.6/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+0.9/wi*this.w, this.y+0.6/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+1.2/wi*this.w, this.y+0.6/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+1.5/wi*this.w, this.y+0.6/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+1.8/wi*this.w, this.y+0.6/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+2.1/wi*this.w, this.y+0.6/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+2.4/wi*this.w, this.y+0.6/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+2.7/wi*this.w, this.y+0.6/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+3.0/wi*this.w, this.y+0.6/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+3.3/wi*this.w, this.y+0.6/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+3.6/wi*this.w, this.y+0.6/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+3.9/wi*this.w, this.y+0.6/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();

		ctx.beginPath(); 
		ctx.arc(this.x+0.6/wi*this.w, this.y+2.9/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+0.9/wi*this.w, this.y+2.9/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+1.2/wi*this.w, this.y+2.9/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+1.5/wi*this.w, this.y+2.9/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+1.8/wi*this.w, this.y+2.9/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+2.1/wi*this.w, this.y+2.9/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+2.4/wi*this.w, this.y+2.9/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+2.7/wi*this.w, this.y+2.9/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+3.0/wi*this.w, this.y+2.9/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+3.3/wi*this.w, this.y+2.9/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+3.6/wi*this.w, this.y+2.9/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+3.9/wi*this.w, this.y+2.9/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();


		ctx.beginPath(); 
		ctx.arc(this.x+0.3/wi*this.w, this.y+0.85/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+0.1/wi*this.w, this.y+1.15/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+0.1/wi*this.w, this.y+1.45/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+0.1/wi*this.w, this.y+1.75/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+0.1/wi*this.w, this.y+2.05/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+0.1/wi*this.w, this.y+2.35/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+0.3/wi*this.w, this.y+2.65/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();

		ctx.beginPath(); 
		ctx.arc(this.x+4.2/wi*this.w, this.y+0.85/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+4.4/wi*this.w, this.y+1.15/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+4.4/wi*this.w, this.y+1.45/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+4.4/wi*this.w, this.y+1.75/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+4.4/wi*this.w, this.y+2.05/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+4.4/wi*this.w, this.y+2.35/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
		ctx.beginPath(); 
		ctx.arc(this.x+4.15/wi*this.w, this.y+2.65/he*this.h, 0.05/wi*this.w, 0, 2*Math.PI, true);
		ctx.closePath(); 
		ctx.stroke(); 
		ctx.fill();
	}
}